## 100 NUMPY EXERCISES

In [ ]:
# 1. Import the numpy package under the name np (★☆☆)
import numpy as np

In [29]:
# 2. Print the numpy version and the configuration (★☆☆)
print('numpy version:', np.__version__)
np.show_config()

numpy version: 2.3.5
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/HP/anaconda3/Library/include
    lib directory: C:/Users/HP/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\miniconda3\conda-bld\numpy_and_numpy_base_1763980694785\_h_env\Library\lib\pkgconfig
    version: '2025'
  lapack:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/HP/anaconda3/Library/include
    lib directory: C:/Users/HP/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\miniconda3\conda-bld\numpy_and_numpy_base_1763980694785\_h_env\Library\lib\pkgconfig
    version: '2025'
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30159
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30159
  cython:
    commands: cython
    linker: cython
    name: cython
 

In [ ]:
# 3. Create a null vector of size 10 (★☆☆)
null_vector = np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
# 4. How to find the memory size of any array (★☆☆)
arr=np.zeros(10)
print(arr.nbytes)
print(arr.nbytes/1024, "KB")

80
0.078125 KB


In [ ]:
# 5. How to get the documentation of the numpy add function from the command line? (★☆☆)
help(np.add)

Help on ufunc in module numpy:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

    Add arguments element-wise.

    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

In [ ]:
# 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
null_vector[4]=1
print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
# 7. Create a vector with values ranging from 10 to 49 (★☆☆)
vector = np.arange(10,50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
# 8. Reverse a vector (first element becomes last) (★☆☆)
Reversed_vector = vector[::-1]
print(Reversed_vector)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [ ]:
# 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
matrix = np.arange(0,9).reshape(3,3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
# 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
arrr = [1,2,0,0,4,0]

In [44]:
indices = np.nonzero(arrr)
print(indices)


(array([0, 1, 4]),)


In [ ]:
# 11. Create a 3x3 identity matrix (★☆☆)
I = np.eye(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# 12. Create a 3x3x3 array with random values (★☆☆)
arr_3d = np.random.rand(3,3,3)
print(arr_3d)

[[[0.05975077 0.15169906 0.93819395]
  [0.56600439 0.84881996 0.24565115]
  [0.93782554 0.29859233 0.75878979]]

 [[0.91001242 0.66963908 0.2485835 ]
  [0.21083693 0.41641445 0.0104425 ]
  [0.00510036 0.17092584 0.3054955 ]]

 [[0.17777794 0.22740931 0.32327573]
  [0.24576785 0.69579027 0.87920186]
  [0.91778456 0.08633211 0.70723328]]]


In [ ]:
# 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
ten_by_ten_arr = np.random.rand(10,10)
min_val = ten_by_ten_arr.min()
max_val = ten_by_ten_arr.max()
print(f"Min: {min_val}")
print(f"Max: {max_val}")

Min: 0.006921609064649781
Max: 0.9942926080277608


In [ ]:
# 14. Create a random vector of size 30 and find the mean value (★☆☆)
vector = np.random.rand(30)
mean_val = vector.mean()

print(vector)
print(f"\nMean: {mean_val}")

[0.71156066 0.3334465  0.47993741 0.74401752 0.15295846 0.43610488
 0.13812782 0.23957585 0.50247653 0.0704608  0.89357312 0.22379568
 0.21939898 0.80965268 0.37128677 0.47803531 0.75446744 0.02834552
 0.98799356 0.147851   0.76145115 0.04054105 0.54555045 0.23986113
 0.12968157 0.30656035 0.49105812 0.42023532 0.33178991 0.74999824]

Mean: 0.424659792918311


In [ ]:
# 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)
arr_1 = np.ones((8,8), dtype=int)
arr_1[1:-1,1:-1]=0
print(arr_1)

[[1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1]]


In [ ]:
# 16. How to add a border (filled with 0's) around an existing array? (★☆☆)
arr_3 = np.zeros((6,6), dtype=int)
arr_3[1:-1,1:-1]=1
print(arr_3)

[[0 0 0 0 0 0]
 [0 1 1 1 1 0]
 [0 1 1 1 1 0]
 [0 1 1 1 1 0]
 [0 1 1 1 1 0]
 [0 0 0 0 0 0]]


In [ ]:
# 17. What is the result of the following expression? (★☆☆)
print(0*np.nan)
print(np.nan==np.nan)
print(np.inf>np.nan)
print(np.nan-np.nan)
print(np.nan in set([np.nan]))
print(0.3==3*0.1)

nan
False
False
nan
True
False


In [ ]:
# 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
num = [1,2,3,4]
matr = np.diag(num, k=-1)
print(matr)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [ ]:
# 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)
checkerboard = (np.indices((8,8)).sum(axis=0)%2)
print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
# 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?
idx = np.unravel_index(99,(6,7,8))
print(idx)

(np.int64(1), np.int64(5), np.int64(3))


In [ ]:
# 21. Create a checkerboard 8x8 matrix using the tile function
base_tile = np.array([[0,1],[1,0]])
board = np.tile(base_tile, (4,4))
print (board)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [112]:
# 22.
np.random.seed(0)
mat = np.random.rand(5,5)

mat_z = (mat-mat.mean())/mat.std()

print(mat_z)
print(f"\nMean:,{mat_z.mean()},\nStd:,{mat_z.std()}")

[[-0.14854421  0.44055117  0.04247881 -0.1624605  -0.59169993]
 [ 0.19519398 -0.54236874  1.06578972  1.32033341 -0.73408512]
 [ 0.71154487 -0.21907095 -0.08045184  1.18555078 -1.84023484]
 [-1.78325269 -2.02016749  0.85634317  0.66350295  0.98873998]
 [ 1.37328739  0.73786513 -0.4577726   0.67190312 -1.67297558]]

Mean:,-7.105427357601002e-17,
Std:,0.9999999999999999


In [117]:
import numpy.char as char

In [128]:
# 23.
RGBA = np.dtype([('r',np.uint8),('g',np.uint8),('b',np.uint8),('a',np.uint8)])

colors = np.array([(255,0,0,255),(0,255,0,128)], dtype=RGBA)

print(colors)
print(colors.dtype)
print(colors['r'])
print(colors[0])
print(colors[0]['g'])

[(255,   0, 0, 255) (  0, 255, 0, 128)]
[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]
[255   0]
(255, 0, 0, 255)
0


In [5]:
import numpy as np

In [6]:
# 24.
np.random.seed(0)
A = np.random.rand(5,3)
B = np.random.rand(3,2)
C = np.dot(A,B)

print("A shape:",A.shape)
print("B shape:",B.shape)
print("C shape:",C.shape)
print("\nC=\n",C)

A shape: (5, 3)
B shape: (3, 2)
C shape: (5, 2)

C=
 [[1.16771006 1.15750086]
 [0.96215441 0.97277033]
 [1.61903287 1.64584455]
 [1.15275998 1.14142503]
 [0.88196569 0.80126141]]


In [7]:
# 25.
arr = np.array([1,2,3,4,5,6,7,8,9])
# negate elements where 3<x<8
negate = (arr>3) & (arr<8)
arr[negate] *=-1
print(arr)

[ 1  2  3 -4 -5 -6 -7  8  9]


In [23]:
# 26.
print(sum(range(5),-1))
from numpy import* 
print(sum(range(5),-1))

10
10


In [30]:
# 27.
Z = np.array ([1,2,3])
print (Z**Z)
print(2<<Z>>2)
print(Z<-Z)
print(1j*Z)
print(Z/1/1)
print(Z<Z>Z)

[ 1  4 27]
[1 2 4]
[False False False]
[0.+1.j 0.+2.j 0.+3.j]
[1. 2. 3.]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [39]:
# 28.
np.array(0)/np.array(0)

C:\Users\HP\AppData\Local\Temp\ipykernel_9880\2701240578.py:2: RuntimeWarning: invalid value encountered in divide
  np.array(0)/np.array(0)


np.float64(nan)

In [40]:
np.array(0)//np.array(0)

C:\Users\HP\AppData\Local\Temp\ipykernel_9880\3350367291.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0)//np.array(0)


np.int64(0)

In [41]:
np.array([np.nan]).astype(int).astype(float)

C:\Users\HP\AppData\Local\Temp\ipykernel_9880\699728972.py:1: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

In [43]:
# 29.
# how to find common values btw two arrays
a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7])

np.intersect1d(a,b)

array([4, 5])

In [45]:
# 30.
# How to round away from zero a float array
x = np.array([1.2,-1.2,0.4,-0.4,0,3.7,-3.7])
result = np.sign(x)*np.ceil(np.abs(x))
print(result)

[ 2. -2.  1. -1.  0.  4. -4.]


In [ ]:
# 31.
# how to ignore all numpy warnings
np.seterr(all='ignore')

In [46]:
# 32.
# is the following expression true
np.sqrt(-1) == np.emath.sqrt(-1)

C:\Users\HP\AppData\Local\Temp\ipykernel_9880\2756021929.py:3: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


np.False_

In [49]:
# 33.
# How to get the dates of yesterday, today and tomorrow
today = np.datetime64('today', 'D')
yesterday = today-np.timedelta64(1,'D')
tomorrow = today+np.timedelta64(1,'D')

print(yesterday)
print(today)
print(tomorrow)


2026-06-02
2026-06-03
2026-06-04


In [55]:
# 34. How to get all dates corresponding to the month of July 2016
start = np.datetime64('2016-07-01')
end = np.datetime64('2016-08-01')

dates = np.arange(start, end, np.timedelta64(1,'D'))
print(dates)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [58]:
# 35. how to compute ((A+B)*(A/2)) in place (without copy)

# compute factor = -A/2, store in B
np.multiply(-A/2,out=B) # B= -A/2

# Now A= A+B
np.add(A,B, out=A) # A=A+(-A/2)= A/2

np.add(A,B, out=A)
np.multiply(A,B, out=A)


TypeError: multiply() takes from 2 to 3 positional arguments but 1 were given

In [73]:
# 36. Extract the integer part of a random array of positive numbers using 4 different methods
x = np.random.rand(5)*10 

# 1. astype(int)
print(x.astype(int))

# 2. n.floor - round down
print(np.floor(x))

# 3.np.trunc - truncate toward 0
print(np.trunc(x))

# 4. np.modf - split frac + int parts
frac, integer = np.modf(x)
integer

[5 0 5 9 3]
[5. 0. 5. 9. 3.]
[5. 0. 5. 9. 3.]


array([5., 0., 5., 9., 3.])

In [75]:
# 37. Create a 5x5 matrix with row values ranging from 0 t0 4
m = np.tile(np.arange(5),(5,1))
m

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [77]:
# 38. Consider a generator function that generates 10 integers and use it to build an array
def gen_10_ints():
    for i in range(10):
        yield i 

arr = np.array(list(gen_10_ints()))
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [80]:
# 39. create a vector of size 10 with values ranging from 0 t0 1, both excluded.
x = np.linspace(0,1,12)[1:-1]
x

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

In [84]:
# 40. Create a random vector of size 10 and sort it
x = np.random.randint(0,100,10)
x.sort()
print (x)


[16 21 24 25 29 56 60 75 77 80]


In [86]:
# 41. How to sum a small array faster than np.sum
n = np.array([1,2,3,4,5])
Sum = sum(n)
print(Sum)

15


In [89]:
# 42. Consider two random array A and B, Check if they are equal
A = np.random.randint(0,10,5)
B = np.random.randint(0,10,5)

Equal = np.array_equal(A,B)
Equal

False

In [90]:
# 43. Make an array immutable (read_only)
xn = np.array([1,2,3,4,5])

xn.flags.writeable = False
xn[0]=99

ValueError: assignment destination is read-only

In [97]:
# 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates
coords = np.random.rand(10,2)*10

x,y = coords[:,0],coords[:,1]

r = np.hypot(x,y)
theta = np.arctan2(y,x)

polar = np.column_stack((r,theta))
print((polar),'\n')
print(coords)

[[1.01225950e+01 1.00518912e+00]
 [8.84502275e+00 5.71734031e-01]
 [9.09364154e+00 7.30911954e-01]
 [8.55113627e+00 5.81223030e-01]
 [1.01466403e+01 1.10467559e+00]
 [2.67153405e+00 1.03137561e+00]
 [1.26300331e+01 7.98185509e-01]
 [7.22811718e+00 4.65863439e-01]
 [5.19711197e+00 1.06514667e-04]
 [5.27509060e+00 9.38257801e-01]] 

[[5.42498775e+00 8.54613580e+00]
 [7.43834545e+00 4.78596326e+00]
 [6.77081574e+00 6.07045061e+00]
 [7.14696936e+00 4.69497183e+00]
 [4.56014623e+00 9.06418087e+00]
 [1.37220420e+00 2.29219323e+00]
 [8.81585399e+00 9.04424976e+00]
 [6.45784599e+00 3.24682972e+00]
 [5.19711194e+00 5.53568650e-04]
 [3.11860221e+00 4.25451538e+00]]


In [104]:
# 45.
xr = np.random.rand(10)
xr[xr.argmax()]=0

xr

array([0.97425866, 0.86230978, 0.78042665, 0.        , 0.75356961,
       0.00404811, 0.26947943, 0.41049214, 0.42822383, 0.29784182])

In [107]:
# 46.
n = 5
dt = np.dtype([('x',float),('y',float)])

x =np.linspace(0,1,n)
y=np.linspace(0,1,n)
xx,yy=np.meshgrid(x,y)

coord = np.zeros(xx.size,dtype=dt)
coord['x']=xx.ravel()
coord['y']=yy.ravel()

coord

array([(0.  , 0.  ), (0.25, 0.  ), (0.5 , 0.  ), (0.75, 0.  ),
       (1.  , 0.  ), (0.  , 0.25), (0.25, 0.25), (0.5 , 0.25),
       (0.75, 0.25), (1.  , 0.25), (0.  , 0.5 ), (0.25, 0.5 ),
       (0.5 , 0.5 ), (0.75, 0.5 ), (1.  , 0.5 ), (0.  , 0.75),
       (0.25, 0.75), (0.5 , 0.75), (0.75, 0.75), (1.  , 0.75),
       (0.  , 1.  ), (0.25, 1.  ), (0.5 , 1.  ), (0.75, 1.  ),
       (1.  , 1.  )], dtype=[('x', '<f8'), ('y', '<f8')])

In [114]:
# 47. Given two arrays, X and Y, construct the Cauchy matrix C(Cij=1/(xi-yj))
X=np.array([1,2,3])
Y=np.array([0,1.5,4])

C=1.0/(X[:,None]-Y)

print(X)
print(Y)
print(C)

[1 2 3]
[0.  1.5 4. ]
[[ 1.         -2.         -0.33333333]
 [ 0.5         2.         -0.5       ]
 [ 0.33333333  0.66666667 -1.        ]]


In [ ]:
# 48. Print the minimum and maximum representable value for each numpy scaler type
import numpy as np

# Integer types
int_types = [np.int8, np.int16, np.int32, np.int64, 
             np.uint8, np.uint16, np.uint32, np.uint64]

print("**Integers**")
for dt in int_types:
    info = np.iinfo(dt)
    print(f"{dt.__name__:>8}: min={info.min:>20}  max={info.max}")

# Float types  
float_types = [np.float16, np.float32, np.float64, np.longdouble]

print("\n**Floats**")
for dt in float_types:
    info = np.finfo(dt)
    print(f"{dt.__name__:>8}: min={info.min:.3e}  max={info.max:.3e}")

# Boolean + complex
print(f"\n{'bool':>8}: min=False  max=True")
print(f"{'complex64':>8}: min=-3.403e+38+3.403e+38j  max=3.403e+38-3.403e+38j")
print(f"{'complex128':>8}: min=-1.798e+308+1.798e+308j  max=1.798e+308-1.798e+308j")


**Integers**
    int8: min=                -128  max=127
   int16: min=              -32768  max=32767
   int32: min=         -2147483648  max=2147483647
   int64: min=-9223372036854775808  max=9223372036854775807
   uint8: min=                   0  max=255
  uint16: min=                   0  max=65535
  uint32: min=                   0  max=4294967295
  uint64: min=                   0  max=18446744073709551615

**Floats**
 float16: min=-6.550e+04  max=6.550e+04
 float32: min=-3.403e+38  max=3.403e+38
 float64: min=-1.798e+308  max=1.798e+308
longdouble: min=-1.798e+308  max=1.798e+308

    bool: min=False  max=True
complex64: min=-3.403e+38+3.403e+38j  max=3.403e+38-3.403e+38j
complex128: min=-1.798e+308+1.798e+308j  max=1.798e+308-1.798e+308j


In [112]:
# 49. How to print all the values of an array
a = np.arange(100)
print(np.array2string(a, threshold=np.inf))


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [113]:
# 50. How to find the closest value(to a given scaler) in a vector
v = np.array([1,3,7,9,12])
scaler=8

idx=np.abs(v-scaler).argmin()
closest =v[idx]

print(idx)
print(closest)

2
7


In [115]:
# 51. Create a structured array representing a position (x,y) and a color (r,g,b) 
dt = np.dtype([('x', float), ('y', float),
               ('r', np.uint8), ('g', np.uint8), ('b', np.uint8)])

arr = np.zeros(5, dtype=dt) # 5 particles
arr['x'] = np.random.rand(5)
arr['y'] = np.random.rand(5)
arr['r'] = np.random.randint(0, 256, 5)
arr['g'] = np.random.randint(0, 256, 5)
arr['b'] = np.random.randint(0, 256, 5)

print(arr[0]) # (0.23, 0.81, 255, 12, 34)


(0.40113234155862765, 0.3436055031480987, 198, 163, 74)


In [116]:
# 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances.

points = np.random.rand(100, 2) # shape (100, 2) = 100 (x,y) coords

# differences between consecutive points: shape (99, 2)
deltas = np.diff(points, axis=0)

# Euclidean distance for each pair
distances = np.linalg.norm(deltas, axis=1) # shape (99,)

# distances[i] = distance from points[i] to points[i+1]


In [120]:
# 53. How to convert a float (32 bits) array into an integer (32 bits) in place?
arr = np.array([1.0, 2.5, -3.0], dtype=np.float32)
arr_int = arr.view(np.int32)  # same memory, new 
print(arr)
print(arr_int)


[ 1.   2.5 -3. ]
[ 1065353216  1075838976 -1069547520]


In [121]:
# 54. How to read the following file?

from io import StringIO

data = """1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11"""

arr = np.genfromtxt(StringIO(data), delimiter=',', dtype=float)
print(arr)


[[ 1.  2.  3.  4.  5.]
 [ 6. nan nan  7.  8.]
 [nan nan  9. 10. 11.]]


In [122]:
# 55. What is the equivalent of enumerate for numpy arrays?

a = np.array([[1, 2], [3, 4]])

for idx, val in np.ndenumerate(a):
    print(idx, val)


(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4


In [123]:
# 56. Generate a generic 2D Gaussian-like array

def gaussian_2d(shape=(100, 100), center=None, sigma=(10, 10)):
    """
    shape: (rows, cols) = (y, x)
    center: (μx, μy). Default = center of array
    sigma: (σx, σy) std dev in x and y
    """
    h, w = shape
    if center is None:
        center = (w/2, h/2) # x, y
    
    x = np.arange(w)
    y = np.arange(h)
    X, Y = np.meshgrid(x, y)
    
    cx, cy = center
    sx, sy = sigma
    
    g = np.exp(-((X-cx)**2/(2*sx**2) + (Y-cy)**2/(2*sy**2)))
    return g

g = gaussian_2d(shape=(200, 200), center=(100, 80), sigma=(20, 40))
print(g.shape)
print(g.max()) 


(200, 200)
1.0


In [124]:
# 57. How to randomly place p elements in a 2D array?
import numpy as np

shape = (10, 10)
p = 15

arr = np.zeros(shape, dtype=int)

# choose p unique flat indices
idx = np.random.choice(arr.size, size=p, replace=False)
arr.flat[idx] = 1

print(arr)


[[0 0 0 0 1 0 0 0 1 0]
 [0 1 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 1 0 0]
 [0 0 0 0 1 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 1 1 0]
 [0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 0 0 0]]


In [125]:
# 58. Subtract the mean of each row of a matrix

A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

A_centered = A - A.mean(axis=1, keepdims=True)
print(A_centered)


[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


In [126]:
# 59. How to sort an array by the nth column?

A = np.array([[3, 2, 1],
              [1, 5, 6],
              [2, 0, 4]])

n = 1  # sort by 2nd column, 0-based indexing

A_sorted = A[A[:, n].argsort()]
print(A_sorted)

[[2 0 4]
 [3 2 1]
 [1 5 6]]


In [127]:
# 60. How to tell if a given 2D array has null columns?

A = np.array([[1, 0, 3],
              [2, 0, 4],
              [5, 0, 6]])

null_cols = np.all(A == 0, axis=0)
print(null_cols)
print(np.where(null_cols)[0])


[False  True False]
[1]


In [129]:
# 61. Find the nearest value from a given value in an array

arr = np.array([1, 4, 8, 15, 23])
target = 10

idx = np.abs(arr - target).argmin()
nearest = arr[idx]

print(nearest)
print(idx)

8
2


In [131]:
# 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator?

A = np.array([[1, 2, 3]]) # shape (1,3)
B = np.array([[4], [5], [6]]) # shape (3,1)

result = np.zeros((3,3))

it = np.nditer([A, B, result],
               flags=['external_loop', 'buffered'],
               op_flags=[['readonly'], ['readonly'], ['writeonly']])

for a, b, c in it:
    c[...] = a + b # broadcasting happens inside

print(result)

[[5. 6. 7.]
 [6. 7. 8.]
 [7. 8. 9.]]


In [132]:
# 63. Create an array class that has a name attribute 

class NamedArray(np.ndarray):
    def __new__(cls, input_array, name=""):
        # Convert input to ndarray, then view as NamedArray
        obj = np.asarray(input_array).view(cls)
        obj.name = name
        return obj
    
    def __array_finalize__(self, obj):
        # Called when new arrays are created from this one
        if obj is None: return
        self.name = getattr(obj, 'name', "")

# Usage
a = NamedArray([[1, 2, 3], [4, 5, 6]], name="my_matrix")
print(a.name)
print(a.shape) 
print(a + 10)


my_matrix
(2, 3)
[[11 12 13]
 [14 15 16]]


In [133]:
# 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

v = np.array([0, 0, 0])
idx = np.array([0, 1, 0, 0])

np.add.at(v, idx, 1)
print(v)


[3 1 0]


In [134]:
# 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)?

F = np.zeros(5)              # destination array
X = np.array([10, 20, 30])   # values to accumulate  
I = np.array([1, 3, 1])      # indices in F for each X

np.add.at(F, I, X)
print(F)


[ 0. 40.  0. 20.  0.]


In [135]:
# 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors 

# img shape: (h, w, 3), dtype=uint8
img = np.random.randint(0, 256, (100, 150, 3), dtype=np.uint8)

pixels = img.reshape(-1, 3) # (h*w, 3)
unique_colors = np.unique(pixels, axis=0)

count = unique_colors.shape[0]
print(count)

14993


In [136]:
# 67. Considering a four dimensions array, how to get sum over the last two axis at once?	

A = np.random.rand(2, 3, 4, 5) # shape (2, 3, 4, 5)

# Sum over last two axes: axis 2 and 3
result = A.sum(axis=(-2, -1))

print(result.shape)

(2, 3)


In [137]:
# 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset indices?

D = np.array([1, 2, 3, 4, 5, 6])      # data
S = np.array([0, 1, 0, 1, 2, 0])      # subset index for each element

# Sum per subset
sums = np.bincount(S, weights=D)

# Count per subset  
counts = np.bincount(S)

# Mean per subset
means = sums / counts

print(means)

[3.33333333 3.         5.        ]


In [140]:
# 69. How to get the diagonal of a dot product?

A = np.random.rand(100, 50)
B = np.random.rand(50, 100)

# Bad: computes full 100x100 matrix
# np.diag(A @ B)

# Good 1: elementwise multiply + sum over n
diag = np.sum(A * B.T, axis=1)
print(diag)


[13.11233836 13.91292986 12.05580769 12.25301602 10.44940913 10.09420623
 11.38967286 12.51147797 10.99842394 11.77271736 11.60273076  9.92853587
 11.84508337 13.37233725 12.7321613  11.33292953 10.12013281 14.20284343
 13.55307671 13.28709494 13.14303271 13.57555027 12.17644149 13.28693168
 13.90252812 13.93143687 12.73221628 13.93293569 12.2775639  15.43268029
 12.64517053  9.80249975 11.60311568 14.57251841 11.45446839 13.58866023
 11.04323754 11.12845396 10.21091619 11.39554237 11.84742655 11.83440509
 10.42966954 12.76625456 13.82448044 14.45409492 15.14408518 11.42140329
 12.22157406 11.70524935 10.50587924 12.33701469 11.98214737 12.98469039
  8.69897528 13.280697   10.68110752 13.62992213 11.26604223 15.89138145
 12.53517339 12.89126536 12.02693643 14.43022438 11.2815165  13.95398199
 13.8637137  13.08169473 13.60963713 13.5268648  15.74088815 14.65370131
 14.33180906 12.96583859 13.48905664 13.53807606  9.52403611 12.93536088
 16.05889413 12.51684758 11.75236212 10.96643032 12

In [141]:
# 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? 

v = np.array([1, 2, 3, 4, 5])
k = 3 # zeros to insert

out = np.zeros(len(v) * (k + 1) - k)
out[::k+1] = v

print(out)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


In [142]:
#71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)?

A = np.random.rand(5, 5, 3)  # (h, w, channels)
B = np.random.rand(5, 5)     # (h, w) weights

# Multiply each channel by B
result = A * B[..., np.newaxis]
# or: result = A * B[:, :, None]
# or: result = A * B.reshape(5, 5, 1)

print(result.shape)

(5, 5, 3)


In [146]:
# 72. How to swap two rows of an array? 

A = np.arange(12).reshape(4, 3)
print(A)

i, j = 1, 3
A[[i, j]] = A[[j, i]] # swap rows 1 and 3

print("\n",A)


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

 [[ 0  1  2]
 [ 9 10 11]
 [ 6  7  8]
 [ 3  4  5]]


In [147]:
# 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the triangles (★★★)

triangles = np.array([
    [0, 1, 2],
    [1, 2, 3],
    [2, 3, 4],
    #... 7 more triplets
]) # shape (10, 3)

# 1. Get all 3 edges per triangle
edges = np.stack([
    triangles[:, [0, 1]],
    triangles[:, [1, 2]],
    triangles[:, [2, 0]]
], axis=1).reshape(-1, 2) # shape (30, 2)

# 2. Sort endpoints so edge is unordered: [min, max]
edges.sort(axis=1)

# 3. Unique edges
unique_edges = np.unique(edges, axis=0)

print(unique_edges.shape[0]) # number of unique line segments
print(unique_edges)


7
[[0 1]
 [0 2]
 [1 2]
 [1 3]
 [2 3]
 [2 4]
 [3 4]]


In [148]:
#74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C?

C = np.array([0, 3, 1, 2]) # C[i] = count of value i
# bincount(A) should equal C

indices = np.arange(len(C)) # [0, 1, 2, 3]
A = np.repeat(indices, C)

print(A) 
print(np.bincount(A)) 


[1 1 1 2 3 3]
[0 3 1 2]


In [151]:
# 75. How to compute averages using a sliding window over an array? 

a = np.array([1, 2, 3, 4, 5, 6])
w = 3  # window size

# 'valid' mode: only full windows
avg = np.convolve(a, np.ones(w)/w, mode='valid')
print(avg)

[2. 3. 4. 5.]


In [153]:
#76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1])
from numpy.lib.stride_tricks import sliding_window_view

Z = np.array([10, 20, 30, 40, 50, 60])
window = 3

A = sliding_window_view(Z, window_shape=window)
print(A)


[[10 20 30]
 [20 30 40]
 [30 40 50]
 [40 50 60]]


In [ ]:
# 77. How to negate a boolean, or to change the sign of a float inplace? 

b = np.array([True, False, True, False])

b[:] = ~b        # Method A: bitwise NOT, inplace
# or
np.logical_not(b, out=b)  # Method B: explicit inplace
print(b)


[ True False  True False]


In [155]:
# 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])?

P0 = np.array([[0,0], [1,1], [2,0]]) # shape (n, 2)
P1 = np.array([[1,0], [2,2], [3,0]]) # shape (n, 2)
p  = np.array([0.5, 0.5])            # shape (2,)

# Vector from P0 to P1 for each line
v = P1 - P0  # (n, 2)

# Vector from P0 to p
w = p - P0   # (n, 2)

# Cross product magnitude in 2D: |v_x * w_y - v_y * w_x|
cross = np.abs(v[:,0]*w[:,1] - v[:,1]*w[:,0])

# Line length
norm_v = np.linalg.norm(v, axis=1)

# Distance = |cross| / |v|
dist = cross / norm_v
print(dist)


[0.5 0.  0.5]


In [156]:
# 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])?

P0 = np.array([[0,0], [1,1]])     # shape (n_lines, 2)
P1 = np.array([[1,0], [2,2]])     # shape (n_lines, 2)
P  = np.array([[0.5,0.5], [3,1]]) # shape (n_points, 2)

# Add axes for broadcasting: (n_lines,1,2) vs (1,n_points,2) vs (n_points,1,2)
v = P1[:, None, :] - P0[:, None, :]  # (n_lines, 1, 2) line vectors
w = P[None, :, :] - P0[:, None, :]   # (n_lines, n_points, 2) vec from P0 to each P

# 2D cross product |v x w| for all pairs
cross = np.abs(v[...,0]*w[...,1] - v[...,1]*w[...,0])  # (n_lines, n_points)

# Line lengths, keep dim for broadcast
norm_v = np.linalg.norm(v, axis=2)  # (n_lines, 1)

# Distance matrix: rows=lines, cols=points
dist = cross / norm_v  # (n_lines, n_points)
dist = dist.T          # (n_points, n_lines) if you want points as rows


In [163]:
# 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a fill value when necessary)

def extract_centered(arr, center, shape, fill=0):
    """
    arr: n-dim array
    center: tuple of indices, e.g. (i,j) for 2D
    shape: tuple of output shape, e.g. (5,5)
    fill: value used for padding
    """
    arr = np.asarray(arr)
    center = np.asarray(center)
    shape = np.asarray(shape)

    # Half window on each side. For even shapes, bias right/bottom
    half = shape // 2
    extra = shape % 2 # handles even sizes

    # Amount to pad: [before, after] for each axis
    pad_width = [(h, h + e) for h, e in zip(half, extra)]
    arr_padded = np.pad(arr, pad_width, mode='constant', constant_values=fill)

    # Adjust center because of padding
    center_pad = center + half

    # Build slices for each dim
    slices = tuple(slice(c - h, c + h + e)
                   for c, h, e in zip(center_pad, half, extra))

    return arr_padded[slices]

A = np.arange(25).reshape(5,5)
print (A)
# center at (2,2), 3x3 window
print('\n',(extract_centered(A,(2,2),(3,3))),'\n')
# Center at corner (0,0), 3x3 window, pad with -1
print(extract_centered(A,(0,0),(3,3),fill=-1))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

 [[ 6  7  8]
 [11 12 13]
 [16 17 18]] 

[[-1 -1 -1]
 [-1  0  1]
 [-1  5  6]]


In [164]:
# 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)
Z = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14])
R = np.array([Z[i:i+4] for i in range(len(Z)-3)])
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


In [165]:
# 82. Compute a matrix rank (★★★)
A = np.random.rand(5, 5)
rank = np.linalg.matrix_rank(A)
print(rank)

5


In [166]:
# 83. How to find the most frequent value in an array?
arr = np.array([1, 2, 2, 3, 3, 3, 4])
values, counts = np.unique(arr, return_counts=True)
most_frequent_value = values[np.argmax(counts)]
print(most_frequent_value)

3


In [168]:
# 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)
A = np.random.rand(10, 10)
blocks = np.array([A[i:i+3, j:j+3] for i in range(8) for j in range(8)])
print(blocks.shape)

(64, 3, 3)


In [2]:
# 85. Create a 2D array subclass such that Z[i,j]==Z[j,i]
import numpy as np
class SymmetricArray(np.ndarray):
    def __new__(cls, input_array):
        obj = np.asarray(input_array).view(cls)
        i_upper = np.triu_indices_from(obj, k=1)
        obj[i_upper] = obj.T[i_upper]
        return obj
    
    def __setitem__(self, index, value):
        super().__setitem__(index, value)
        if isinstance(index, tuple) and len(index) == 2:
            i, j = index
        # Ensure symmetry: Z[i,j] = Z[j,i]
        super().__setitem__((j, i), value)

# usage
Z = SymmetricArray(np.zeros((4,4)))
Z[0, 3] = 5
print(Z)
print(Z[0,3]==Z[3,0])

[[0. 0. 0. 5.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [5. 0. 0. 0.]]
True


In [5]:
# 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of the matrix products at once? (block size is 4x4)
n, p = 5, 10
A = np.random.rand(p, n, n)
V = np.random.rand(p, n, 1)
result = np.einsum('pij,pjk->ik', A, V)
print(result.shape)
print (result)


(5, 1)
[[10.52760104]
 [ 9.82519576]
 [12.64083876]
 [12.78872793]
 [11.27712708]]


In [6]:
# 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)?
A = np.random.rand(16, 16)
block_size = 4
block_sum = A.reshape(16//block_size, block_size, 16//block_size, block_size).sum(axis=(1, 3))
print(block_sum.shape)

(4, 4)


In [10]:
# 88. How to implement the Game of Life using numpy arrays? (★★★)
def game_of_life_step(board):
    neighbors = sum(np.roll(np.roll(board, i, 0), j, 1)
                    for i in (-1, 0, 1) for j in (-1, 0, 1)
                    if (i != 0 or j != 0))
    return (neighbors == 3) | (board & (neighbors == 2))
# Example usage
board = np.random.choice([0, 1], size=(5, 5))
print("Initial board:\n", board)
new_board = game_of_life_step(board)
print("New board:\n", new_board)

Initial board:
 [[1 1 1 0 0]
 [1 0 1 1 1]
 [1 1 1 0 0]
 [0 0 1 0 1]
 [1 1 0 0 0]]
New board:
 [[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 1 1 1]
 [0 0 0 1 1]]


In [11]:
# 89. How to get the n largest values of an array
Z = np.array ([5,1,9,3,7,6,2,8,4])

n = 3
largest = np.partition(Z, -n)[-n:]
largest_sorted = np.sort(largest)[::-1]
print(largest_sorted)

[9 8 7]


In [12]:
# 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item)
vectors = [np.array([1, 2]), np.array([3, 4]), np.array([5, 6])]
cartesian_product = np.array(np.meshgrid(*vectors)).T.reshape(-1, len(vectors))
print(cartesian_product)

[[1 3 5]
 [1 4 5]
 [2 3 5]
 [2 4 5]
 [1 3 6]
 [1 4 6]
 [2 3 6]
 [2 4 6]]


In [15]:
# 91. How to create a record array from a regular array?
arr = np.array([[1, 2], [3, 4]], dtype=[('x', int), ('y', int)])
record_arr = arr.view(np.recarray)
print(record_arr, "\n")
print(record_arr.x)

[[(1, 1) (2, 2)]
 [(3, 3) (4, 4)]] 

[[1 2]
 [3 4]]


In [16]:
# 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods
Z = np.random.rand(1000000)

# Method 1: Using ** operator
result1 = Z ** 3

# Method 2: Using np.power
result2 = np.power(Z, 3)

# Method 3: Using np.multiply
result3 = np.multiply(Z, np.multiply(Z, Z))

print("Method 1 result (Z**3):", result1[:5])
print("Method 2 result (Z**3):", result2[:5])
print("Method 3 result (Z**3):", result3[:5])

Method 1 result (Z**3): [0.50899673 0.31667236 0.03550299 0.27185861 0.04977521]
Method 2 result (Z**3): [0.50899673 0.31667236 0.03550299 0.27185861 0.04977521]
Method 3 result (Z**3): [0.50899673 0.31667236 0.03550299 0.27185861 0.04977521]


In [20]:
# 93. Consider two arrays A and B of shape (8,3) and (2,2). how to find rows of A that contain elements of each row of B regardless of the order of the elements in B?
A = np.array([[1, 2, 3],
              [3, 1, 2],
              [4, 5, 6],
              [2, 3, 1],
              [7, 8, 9],
              [1, 4, 2],
              [2, 1, 3],
              [0, 0, 0]])

B = np.array([[1, 2],
    [3, 4]])

def rows_containing_all(A, B_row):
    """ Return boolean mask for rows of A that contain all elements of B_row """
    return np.isin(A,B_row).all(axis=1)

for i, b_row in enumerate(B):
    mask = rows_containing_all(A, b_row)
    print(f"B[{i}]={b_row}->A rows: {np.where(mask)[0]}")
    print(A[mask])

B[0]=[1 2]->A rows: []
[]
B[1]=[3 4]->A rows: []
[]


In [22]:
# 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3])
A = np.array([[1,1,1],
              [2,2,3],
              [4,5,4],
              [7,7,7],
              [0,1,2],
              [3,3,3],
              [8,9,8],
              [6,6,6],
              [2,3,4],
              [9,9,9]
              ])

# method 1: compare to first col
mask = ~np.all(A == A[:,[0]], axis=1)

# method 2: count unique per row
# mask = np.apply_along_axis(lambda r: np.unique(r).size > 1, 1, A)

rows_unequal = A[mask]
row_idx = np.where(mask)[0]

print("indices:", row_idx)
print(rows_unequal)

indices: [1 2 4 6 8]
[[2 2 3]
 [4 5 4]
 [0 1 2]
 [8 9 8]
 [2 3 4]]


In [23]:
# 95. Convert a vector of ints into a matrix binary representation (★★★)
ints = np.array([0, 1, 2, 3, 4, 5, 6, 7])
n_bits = 3
binary_matrix = np.unpackbits(ints[:, np.newaxis].astype(np.uint8), axis=1)[:, -n_bits:]
print(binary_matrix)

[[0 0 0]
 [0 0 1]
 [0 1 0]
 [0 1 1]
 [1 0 0]
 [1 0 1]
 [1 1 0]
 [1 1 1]]


In [24]:
# 96. Given a two dimensional array, how to extract unique rows?
A = np.array([[1, 2],
              [3, 4],
              [1, 2],
              [5, 6],
              [3, 4]])
unique_rows = np.unique(A, axis=0)
print(unique_rows)

[[1 2]
 [3 4]
 [5 6]]


In [25]:
# 97. Considering 2 vectors A & B, write thr einsum equivqlent of inner, outer, sum and mul function
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])
inner_product = np.einsum('i,i->', A, B)
outer_product = np.einsum('i,j->ij', A, B)
sum_vectors = np.einsum('i->', A) + np.einsum('i->', B)
mul_vectors = np.einsum('i,i->i', A, B)
print("Inner product:", inner_product)
print("Outer product:\n", outer_product)
print("Sum of vectors:", sum_vectors)
print("Element-wise multiplication:", mul_vectors)

Inner product: 32
Outer product:
 [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
Sum of vectors: 21
Element-wise multiplication: [ 4 10 18]


In [26]:
# 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples?
X = np.array([0, 1, 2, 3])
Y = np.array([0, 1, 0, -1])
points = np.column_stack((X, Y))
distances = np.sqrt(np.sum(np.diff(points, axis=0)**2, axis=1))
cumulative_distances = np.insert(np.cumsum(distances), 0, 0)
total_length = cumulative_distances[-1]
n_samples = 5
sampled_distances = np.linspace(0, total_length, n_samples)
sampled_points = np.empty((n_samples, 2))
for i, d in enumerate(sampled_distances):
    idx = np.searchsorted(cumulative_distances, d) - 1
    if idx >= len(points) - 1:
        sampled_points[i] = points[-1]
    else:
        t = (d - cumulative_distances[idx]) / distances[idx]
        sampled_points[i] = (1 - t) * points[idx] + t * points[idx + 1]
print(sampled_points)


[[12.   -4.  ]
 [ 0.75  0.75]
 [ 1.5   0.5 ]
 [ 2.25 -0.25]
 [ 3.   -1.  ]]


In [27]:
# 99. Given an integer n and a 2D array X, select from X the rows which can be intepereted as draws fron a multinomial distributon with n degrees, i.e., the rows which only contain integers and which sum to n.
def multinomial_rows(X, n):
    """ Return rows of X that are valid multinomial draws with n trials """
    X = np.asarray(X)
    # Check if all elements are integers and rows sum to n
    is_integer = np.all(np.mod(X, 1) == 0, axis=1)
    sums_to_n = np.sum(X, axis=1) == n
    valid_rows = X[is_integer & sums_to_n]
    return valid_rows
# Example usage
X = np.array([[2, 1, 0], 
              [1, 2, 2], 
              [0, 0, 3]])
n = 3
result = multinomial_rows(X, n)
print(result)

[[2 1 0]
 [0 0 3]]


In [28]:
# 100. Compute bootsrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means).
def bootstrap_confidence_interval(X, N=1000, alpha=0.05):
    """ Compute bootstrap confidence interval for mean of X """
    X = np.asarray(X)
    means = np.empty(N)
    for i in range(N):
        sample = np.random.choice(X, size=len(X), replace=True)
        means[i] = np.mean(sample)
    lower = np.percentile(means, 100 * (alpha / 2))
    upper = np.percentile(means, 100 * (1 - alpha / 2))
    return lower, upper
# Example usage
X = np.random.rand(100)  # Sample data
lower, upper = bootstrap_confidence_interval(X)
print(f"95% confidence interval for the mean: [{lower:.2f}, {upper:.2f}]")


95% confidence interval for the mean: [0.48, 0.59]
